#!/usr/bin/env python3
import sys
import os
import re

if len(sys.argv) != 4:
    print("Usage: replace path oldpattern newpattern")
    sys.exit(1)

path = sys.argv[1]
oldpattern = sys.argv[2]
newpattern = sys.argv[3]

for root, dirs, files in os.walk(path):
    for file in files:
        file_path = os.path.join(root, file)
        with open(file_path, 'r') as f:
            content = f.read()
        new_content = re.sub(oldpattern, newpattern, content)
        with open(file_path, 'w') as f:
            f.write(new_content)
        new_file_path = os.path.join(root, file.replace(oldpattern, newpattern))
        os.rename(file_path, new_file_path)

